# Generated by Django 6.1 on 2026-08-14 15:31

import django.db.models.deletion
import django_extensions.db.fields
import shared.utils.fields
import youtube.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True)),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('title', shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('description', shared.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('total_watch', models.PositiveSmallIntegerField(default=0)),
                ('next_video', models.CharField(blank=True, max_length=255, null=True)),
                ('has_new_video', models.BooleanField(default=False)),
                ('checkout', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, youtube.models.AutoEncryptHashMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True)),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('title', shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('next_video', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.channel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, youtube.models.AutoEncryptHashMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', models.DurationField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(youtube.models.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True)),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('title', shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('description', shared.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('start_from', models.PositiveSmallIntegerField(default=0)),
                ('checkout', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('watched', 'Watched'), ('skipped', 'Skipped'), ('archived', 'Archived')], default='new', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('channels', models.ManyToManyField(blank=True, to='youtube.channel')),
                ('labels', models.ManyToManyField(blank=True, to='youtube.label')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.priority')),
                ('reminders', models.ManyToManyField(blank=True, to='youtube.reminder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'url_hash'), name='unique_user_video')],
            },
            bases=(youtube.models.AuditMixin, youtube.models.AutoEncryptHashMixin, models.Model),
        ),
    ]
