# Generated by Django 6.1 on 2026-08-14 16:43

import django.db.models.deletion
import shared.utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit Jurnali', 'verbose_name_plural': 'Audit Jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Kanal', 'verbose_name_plural': 'Kanallar'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Yorliq', 'verbose_name_plural': 'Yorliqlar'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Pleylist', 'verbose_name_plural': 'Pleylistlar'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Muhimlik', 'verbose_name_plural': 'Muhimlik darajalari'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Eslatma', 'verbose_name_plural': 'Eslatmalar'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratish'), ('update', 'Yangilash'), ('delete', "O'chirish")], max_length=10, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, null=True, verbose_name="O'zgarishlar"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model nomi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=100, verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='checkout',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Tekshirish vaqti'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='has_new_video',
            field=models.BooleanField(default=False, verbose_name='Yangi video bormi?'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='next_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyingi video'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='total_watch',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ko'rilgan videolar"),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True, verbose_name='Kanal havolasi'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Havola xeshi'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Yorliq nomi'),
        ),
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.channel', verbose_name='Kanal'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tekshirish vaqti'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='next_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyingi video'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True, verbose_name='Pleylist havolasi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Havola xeshi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Muhimlik darajasi'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DurationField(verbose_name='Eslatma vaqti'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channels',
            field=models.ManyToManyField(blank=True, to='youtube.channel', verbose_name='Kanallar'),
        ),
        migrations.AlterField(
            model_name='video',
            name='checkout',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Tekshirish vaqti'),
        ),
        migrations.AlterField(
            model_name='video',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Muddati (Deadline)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Ommaviymi?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='labels',
            field=models.ManyToManyField(blank=True, to='youtube.label', verbose_name='Yorliqlar'),
        ),
        migrations.AlterField(
            model_name='video',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.priority', verbose_name='Muhimligi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='reminders',
            field=models.ManyToManyField(blank=True, to='youtube.reminder', verbose_name='Eslatmalar'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_from',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Shu vaqtdan boshlash (sek)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('watched', "Ko'rilgan"), ('skipped', "O'tkazib yuborilgan"), ('archived', 'Arxivlangan')], default='new', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=shared.utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, unique=True, verbose_name='Havola (URL)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Havola xeshi'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
