# Generated by Django 6.1 on 2026-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_auditlog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Teg', 'verbose_name_plural': 'Teglar'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='labels',
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='youtube.label', verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='youtube.label', verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='youtube.label', verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Teg nomi'),
        ),
    ]
