# Generated by Django 6.1 on 2026-08-15 01:09

import shared.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_label_options_remove_video_labels_channel_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=shared.utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
