# Generated by Django 6.1 on 2026-08-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playlist_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pleylistlar soni'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber_count',
            field=models.BigIntegerField(default=0, verbose_name='Obunachilar soni'),
        ),
        migrations.AddField(
            model_name='channel',
            name='video_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Videolar soni'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='video_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Videolar soni'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (soniya)'),
        ),
    ]
