# Generated by Django 6.1 on 2026-08-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_channel_playlist_count_channel_subscriber_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name="Cookie'lar ishlatilsinmi?")),
                ('cookies', models.TextField(blank=True, help_text="Brauzer cookie'larini netscape formatda eksport qilib shu yerga yopishtiring", verbose_name='cookie.txt (netscape formati)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'YouTube Cookie sozlamasi',
                'verbose_name_plural': 'YouTube Cookie sozlamalari',
            },
        ),
    ]
