# Generated by Django 6.1 on 2026-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_youtubeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirish'),
        ),
    ]
