# Generated by Django 6.1 on 2026-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_channel_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_public',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirish'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirish'),
        ),
    ]
