# Generated by Django 6.1 on 2026-08-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_remove_video_is_public_playlist_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='shorts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Shorts soni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('watched', "Ko'rilgan"), ('skipped', "O'tkazib yuborildi"), ('archived', 'Arxivlangan')], default='new', max_length=20, verbose_name='Holati'),
        ),
    ]
