# Generated by Django 6.1 on 2026-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_channel_shorts_count_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlangan'),
        ),
    ]
