# Generated by Django 6.1 on 2026-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_channel_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlash'),
        ),
    ]
