# Generated by Django 6.1 on 2026-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_alter_channel_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (soniya)'),
        ),
    ]
