# Generated by Django 6.1 on 2026-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_playlist_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='live_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jonli efirlar soni'),
        ),
    ]
