# Generated by Django 6.1 on 2026-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_channel_live_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Jonli efir (Live)'),
        ),
    ]
