# Generated by Django 6.1 on 2026-08-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_video_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.priority', verbose_name='Muhimligi'),
        ),
    ]
