# Generated by Django 6.1 on 2026-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='youtube.playlist', verbose_name='Pleylistlar'),
        ),
    ]
